### ISSUE TITLE
Exception thrown in area_under_curve

### ISSUE THREAD

**Issue by femtomc** [beacon-biosignals/Lighthouse.jl#16]
This is a bit of a weird issue - just popped up during training:

<img width="959" alt="image" src="https://user-images.githubusercontent.com/34410036/103371786-54078800-4a9e-11eb-8b30-6e609ce0345f.png">

Seems like it could be:
1. Types are too loose, letting something in which should throw earlier.
2. This is a bug and we should define `one(::Type{Union{}}) = 1` for example.

**Comment by ericphanson** [comment]
This happens when both arguments to area of the curve are empty. In #15 I added a more clear error to handle this case. I'm not totally sure if there are legit reasons for these arguments to be empty, in which case we should just return zero, or if it always means a bug somewhere and throwing a more clear error is correct.

**Comment by jrevels** [comment]
Seems like [this code](https://github.com/beacon-biosignals/Lighthouse.jl/blob/4ea93408df1b6eb1412900bdaa99a52da4b95c15/src/utilities.jl#L39) should be updated to handle the case where `kept` and/or inputs empty

**Comment by femtomc** [comment]
I suspect that means that training went awry but didn't throw anything. Interesting.
